# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Damien Villeneuve"
description: "#JEE / #Android / #iOS engineer at @BeAppTeam. Love programming, geeky stuffs, new-technologies and cooking"
email: contact@dvilleneuve.fr
# blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/cover-home.jpg"

name: 'Damien Villeneuve'
author: 'Damien Villeneuve'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.dvilleneuve.fr"
baseurl: ""

# social icons and sharing options
social:
  - icon:	user
    url:	http://dvilleneuve.fr
    desc:   Visit my website
    share_url:
    share_title:
    share_link:

  - icon:	twitter
    url:	https://twitter.com/dam_villeneuve
    desc:   Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/DayS
    desc:	Follow me on Github
    share_url:
    share_title:
    share_link:
